version: '3.7'

services:

  mssql:
    container_name: mssql_db_container
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: password1!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes: # persist data even if container shuts down
      - mssql_data:/var/opt/mssql/

volumes: # named volumes can be managed easier using docker-compose
  mssql_data: